import * as z from "zod";
import {
  SHIPPING_METHODS,
  ORDER_STATUSES,
  CONDITIONS,
  CATEGORIES,
  SYNC_SESSION_STATUSES,
  SYNC_TYPES,
} from "@myakiba/constants";
export const sortDirectionSchema = z.enum(["asc", "desc"]);

export const orderSearchSortSchema = z.enum([
  "title",
  "shop",
  "orderDate",
  "paymentDate",
  "shippingDate",
  "collectionDate",
  "releaseDate",
  "shippingMethod",
  "total",
  "shippingFee",
  "taxes",
  "duties",
  "tariffs",
  "miscFees",
  "itemCount",
  "status",
  "createdAt",
]);

export const collectionSearchSortSchema = z.enum([
  "itemTitle",
  "itemCategory",
  "itemScale",
  "status",
  "count",
  "score",
  "price",
  "shop",
  "orderDate",
  "paymentDate",
  "shippingDate",
  "releaseDate",
  "collectionDate",
  "createdAt",
]);

export const searchSchema = z.object({
  limit: z.coerce.number().int().positive().optional(),
  offset: z.coerce.number().int().min(0).optional(),
  sort: orderSearchSortSchema.optional(),
  order: sortDirectionSchema.optional(),
  search: z.string().optional(),
  shop: z.array(z.string()).optional(),
  releaseDateStart: z.iso.date().optional(),
  releaseDateEnd: z.iso.date().optional(),
  shipMethod: z.array(z.enum(SHIPPING_METHODS)).optional(),
  orderDateStart: z.iso.date().optional(),
  orderDateEnd: z.iso.date().optional(),
  payDateStart: z.iso.date().optional(),
  payDateEnd: z.iso.date().optional(),
  shipDateStart: z.iso.date().optional(),
  shipDateEnd: z.iso.date().optional(),
  colDateStart: z.iso.date().optional(),
  colDateEnd: z.iso.date().optional(),
  status: z.array(z.enum(ORDER_STATUSES)).optional(),
  totalMin: z.coerce.number().int().optional(),
  totalMax: z.coerce.number().int().optional(),
  shippingFeeMin: z.coerce.number().int().optional(),
  shippingFeeMax: z.coerce.number().int().optional(),
  taxesMin: z.coerce.number().int().optional(),
  taxesMax: z.coerce.number().int().optional(),
  dutiesMin: z.coerce.number().int().optional(),
  dutiesMax: z.coerce.number().int().optional(),
  tariffsMin: z.coerce.number().int().optional(),
  tariffsMax: z.coerce.number().int().optional(),
  miscFeesMin: z.coerce.number().int().optional(),
  miscFeesMax: z.coerce.number().int().optional(),
});

export const collectionSearchSchema = z.object({
  limit: z.coerce.number().int().positive().optional(),
  offset: z.coerce.number().int().min(0).optional(),
  sort: collectionSearchSortSchema.optional(),
  order: sortDirectionSchema.optional(),
  search: z.string().optional(),
  paidMin: z.coerce.number().int().optional(),
  paidMax: z.coerce.number().int().optional(),
  shop: z.array(z.string()).optional(),
  payDateStart: z.iso.date().optional(),
  payDateEnd: z.iso.date().optional(),
  shipDateStart: z.iso.date().optional(),
  shipDateEnd: z.iso.date().optional(),
  colDateStart: z.iso.date().optional(),
  colDateEnd: z.iso.date().optional(),
  shipMethod: z.array(z.enum(SHIPPING_METHODS)).optional(),
  relDateStart: z.iso.date().optional(),
  relDateEnd: z.iso.date().optional(),
  relPriceMin: z.coerce.number().int().optional(),
  relPriceMax: z.coerce.number().int().optional(),
  relCurrency: z.array(z.string()).optional(),
  category: z.array(z.enum(CATEGORIES)).optional(),
  entries: z.array(z.string()).optional(),
  scale: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
  condition: z.array(z.enum(CONDITIONS)).optional(),
});

export const syncSearchSchema = z.object({
  page: z.coerce.number().int().positive().optional(),
  limit: z.coerce.number().int().positive().optional(),
  status: z.enum(SYNC_SESSION_STATUSES).optional(),
  syncType: z.enum(SYNC_TYPES).optional(),
});

export type OrderFilters = z.infer<typeof searchSchema>;
export type CollectionFilters = z.infer<typeof collectionSearchSchema>;
