import * as z from "zod";
import { SHIPPING_METHODS, ORDER_STATUSES, CONDITIONS, CATEGORIES } from "@myakiba/constants";

export const searchSchema = z.object({
  limit: z.coerce.number().optional(),
  offset: z.coerce.number().optional(),
  sort: z
    .enum([
      "title",
      "shop",
      "orderDate",
      "paymentDate",
      "shippingDate",
      "collectionDate",
      "releaseMonthYear",
      "shippingMethod",
      "total",
      "shippingFee",
      "taxes",
      "duties",
      "tariffs",
      "miscFees",
      "itemCount",
      "status",
      "createdAt",
    ])
    .optional(),
  order: z.enum(["asc", "desc"]).optional(),
  search: z.string().optional(),
  shop: z.array(z.string()).optional(),
  releaseMonthYearStart: z.iso.date().optional(),
  releaseMonthYearEnd: z.iso.date().optional(),
  shipMethod: z.array(z.enum(SHIPPING_METHODS)).optional(),
  orderDateStart: z.iso.date().optional(),
  orderDateEnd: z.iso.date().optional(),
  payDateStart: z.iso.date().optional(),
  payDateEnd: z.iso.date().optional(),
  shipDateStart: z.iso.date().optional(),
  shipDateEnd: z.iso.date().optional(),
  colDateStart: z.iso.date().optional(),
  colDateEnd: z.iso.date().optional(),
  status: z.array(z.enum(ORDER_STATUSES)).optional(),
  totalMin: z.string().optional(),
  totalMax: z.string().optional(),
  shippingFeeMin: z.string().optional(),
  shippingFeeMax: z.string().optional(),
  taxesMin: z.string().optional(),
  taxesMax: z.string().optional(),
  dutiesMin: z.string().optional(),
  dutiesMax: z.string().optional(),
  tariffsMin: z.string().optional(),
  tariffsMax: z.string().optional(),
  miscFeesMin: z.string().optional(),
  miscFeesMax: z.string().optional(),
});

export const collectionSearchSchema = z.object({
  limit: z.coerce.number().optional(),
  offset: z.coerce.number().optional(),
  sort: z
    .enum([
      "itemTitle",
      "itemCategory",
      "itemScale",
      "status",
      "count",
      "score",
      "price",
      "shop",
      "orderDate",
      "paymentDate",
      "shippingDate",
      "releaseDate",
      "collectionDate",
      "createdAt",
    ])
    .optional(),
  order: z.enum(["asc", "desc"]).optional(),
  search: z.string().optional(),
  paidMin: z.string().optional(),
  paidMax: z.string().optional(),
  shop: z.array(z.string()).optional(),
  payDateStart: z.iso.date().optional(),
  payDateEnd: z.iso.date().optional(),
  shipDateStart: z.iso.date().optional(),
  shipDateEnd: z.iso.date().optional(),
  colDateStart: z.iso.date().optional(),
  colDateEnd: z.iso.date().optional(),
  shipMethod: z.array(z.enum(SHIPPING_METHODS)).optional(),
  relDateStart: z.iso.date().optional(),
  relDateEnd: z.iso.date().optional(),
  relPriceMin: z.string().optional(),
  relPriceMax: z.string().optional(),
  relCurrency: z.array(z.string()).optional(),
  category: z.array(z.enum(CATEGORIES)).optional(),
  entries: z.array(z.string()).optional(),
  scale: z.array(z.string()).optional(),
  tags: z.array(z.string()).optional(),
  condition: z.array(z.enum(CONDITIONS)).optional(),
});

