/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as appSyncRouteImport } from './routes/(app)/sync'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appOrdersRouteImport } from './routes/(app)/orders'
import { Route as appGalleryRouteImport } from './routes/(app)/gallery'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appCollectionRouteImport } from './routes/(app)/collection'
import { Route as appAnalyticsRouteImport } from './routes/(app)/analytics'
import { Route as appOrdersIdRouteImport } from './routes/(app)/orders_.$id'
import { Route as appItemsIdRouteImport } from './routes/(app)/items_.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const appSyncRoute = appSyncRouteImport.update({
  id: '/sync',
  path: '/sync',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrdersRoute = appOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => appRouteRoute,
} as any)
const appGalleryRoute = appGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appCollectionRoute = appCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => appRouteRoute,
} as any)
const appAnalyticsRoute = appAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrdersIdRoute = appOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => appRouteRoute,
} as any)
const appItemsIdRoute = appItemsIdRouteImport.update({
  id: '/items_/$id',
  path: '/items/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/analytics': typeof appAnalyticsRoute
  '/collection': typeof appCollectionRoute
  '/dashboard': typeof appDashboardRoute
  '/gallery': typeof appGalleryRoute
  '/orders': typeof appOrdersRoute
  '/settings': typeof appSettingsRoute
  '/sync': typeof appSyncRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/items/$id': typeof appItemsIdRoute
  '/orders/$id': typeof appOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/analytics': typeof appAnalyticsRoute
  '/collection': typeof appCollectionRoute
  '/dashboard': typeof appDashboardRoute
  '/gallery': typeof appGalleryRoute
  '/orders': typeof appOrdersRoute
  '/settings': typeof appSettingsRoute
  '/sync': typeof appSyncRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/items/$id': typeof appItemsIdRoute
  '/orders/$id': typeof appOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(app)/analytics': typeof appAnalyticsRoute
  '/(app)/collection': typeof appCollectionRoute
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/gallery': typeof appGalleryRoute
  '/(app)/orders': typeof appOrdersRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/sync': typeof appSyncRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/(app)/items_/$id': typeof appItemsIdRoute
  '/(app)/orders_/$id': typeof appOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/analytics'
    | '/collection'
    | '/dashboard'
    | '/gallery'
    | '/orders'
    | '/settings'
    | '/sync'
    | '/profile/$username'
    | '/items/$id'
    | '/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/analytics'
    | '/collection'
    | '/dashboard'
    | '/gallery'
    | '/orders'
    | '/settings'
    | '/sync'
    | '/profile/$username'
    | '/items/$id'
    | '/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/login'
    | '/(app)/analytics'
    | '/(app)/collection'
    | '/(app)/dashboard'
    | '/(app)/gallery'
    | '/(app)/orders'
    | '/(app)/settings'
    | '/(app)/sync'
    | '/profile/$username'
    | '/(app)/items_/$id'
    | '/(app)/orders_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/sync': {
      id: '/(app)/sync'
      path: '/sync'
      fullPath: '/sync'
      preLoaderRoute: typeof appSyncRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/orders': {
      id: '/(app)/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof appOrdersRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/gallery': {
      id: '/(app)/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof appGalleryRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/collection': {
      id: '/(app)/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof appCollectionRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/analytics': {
      id: '/(app)/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof appAnalyticsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/orders_/$id': {
      id: '/(app)/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof appOrdersIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/items_/$id': {
      id: '/(app)/items_/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof appItemsIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appAnalyticsRoute: typeof appAnalyticsRoute
  appCollectionRoute: typeof appCollectionRoute
  appDashboardRoute: typeof appDashboardRoute
  appGalleryRoute: typeof appGalleryRoute
  appOrdersRoute: typeof appOrdersRoute
  appSettingsRoute: typeof appSettingsRoute
  appSyncRoute: typeof appSyncRoute
  appItemsIdRoute: typeof appItemsIdRoute
  appOrdersIdRoute: typeof appOrdersIdRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appAnalyticsRoute: appAnalyticsRoute,
  appCollectionRoute: appCollectionRoute,
  appDashboardRoute: appDashboardRoute,
  appGalleryRoute: appGalleryRoute,
  appOrdersRoute: appOrdersRoute,
  appSettingsRoute: appSettingsRoute,
  appSyncRoute: appSyncRoute,
  appItemsIdRoute: appItemsIdRoute,
  appOrdersIdRoute: appOrdersIdRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
