name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.2.3'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Check for build artifacts
        run: |
          echo "Checking build artifacts..."
          find . -name "dist" -type d | head -10
          find . -name "*.js" -path "*/dist/*" | head -10 
          
      - name: Type check
        run: bun run check-types